### ISSUE TITLE
Redlink templates are hidden from the page.

### ISSUE THREAD

**Issue by Alianin** [oOeyes/BoilerRoom#1]
Normally when a template is added to a page and that template doesn't exist, it displays as a redlink. When BoilerRoom is enabled on a wiki, the redlink template no longer shows on page. This can be seen here: https://help.gamepedia.com/index.php?title=User:CrsBenjamin/Sandbox&curid=4037&diff=15327&oldid=14729

**Comment by oOeyes** [comment]
Issue identified and corrected in an soon to be released minor update (1.31). Not releasing immediately since this isn't a critical bug, but since it is prompting an update, this is a good time to modernize BoilerRoom's legacy extension registration code.
